
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import { Globe, Plane, MapPin, Calendar, CreditCard } from "lucide-react";

export default function HeroSection() {
  return (
    <div className="relative hero-pattern py-16 sm:py-24">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="lg:grid lg:grid-cols-12 lg:gap-8">
          <div className="sm:text-center md:max-w-2xl md:mx-auto lg:col-span-6 lg:text-left">
            <h1 className="text-4xl font-extrabold tracking-tight text-gray-900 sm:text-5xl md:text-6xl">
              <span className="block xl:inline">Plan your dream trip with</span>{' '}
              <span className="block gradient-text xl:inline">AI-powered intelligence</span>
            </h1>
            <p className="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg">
              Our intelligent AI system creates personalized travel itineraries based on your preferences, budget, and timeline. Experience smarter travel planning with real-time updates and local recommendations.
            </p>
            <div className="mt-8 sm:max-w-lg sm:mx-auto sm:text-center lg:text-left lg:mx-0">
              <div className="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start">
                <Link to="/create">
                  <Button className="w-full sm:w-auto bg-gradient-to-r from-travel-blue to-travel-purple text-white hover:opacity-90 text-base py-6 px-8">
                    Plan Your Trip
                  </Button>
                </Link>
                <Link to="/features">
                  <Button variant="outline" className="w-full sm:w-auto text-base py-6 px-8">
                    Learn More
                  </Button>
                </Link>
              </div>
              <p className="mt-3 text-sm text-gray-500 flex items-center justify-center lg:justify-start">
                <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800 mr-2">
                  New
                </span>
                Now with real-time weather updates and local event recommendations!
              </p>
            </div>
          </div>
          <div className="mt-12 relative sm:max-w-lg sm:mx-auto lg:mt-0 lg:max-w-none lg:mx-0 lg:col-span-6 lg:flex lg:items-center">
            <div className="relative mx-auto w-full rounded-lg shadow-lg lg:max-w-md">
              <div className="relative block w-full bg-white rounded-lg overflow-hidden">
                <div className="aspect-w-16 aspect-h-9">
                  <div className="p-4 grid grid-cols-1 gap-4 bg-gradient-to-br from-blue-50 to-purple-50 h-full">
                    <div className="rounded-lg bg-white shadow p-4 animate-fade-in">
                      <div className="flex items-center mb-2">
                        <Plane className="h-5 w-5 text-travel-blue mr-2" />
                        <span className="font-medium text-gray-900">Paris Itinerary</span>
                      </div>
                      <div className="flex items-center text-sm text-gray-500 mb-2">
                        <Calendar className="h-4 w-4 mr-1" />
                        <span>April 10-15, 2025</span>
                      </div>
                      <div className="flex items-center text-sm text-gray-500 mb-2">
                        <CreditCard className="h-4 w-4 mr-1" />
                        <span>Budget: $1,200</span>
                      </div>
                      <div className="mt-3 space-y-1">
                        <div className="bg-blue-50 p-2 rounded flex items-start">
                          <div className="bg-travel-blue text-white p-1 rounded mr-2">
                            <span className="text-xs">Day 1</span>
                          </div>
                          <div className="text-sm">
                            <p>Visit Eiffel Tower & Louvre Museum</p>
                          </div>
                        </div>
                        <div className="bg-blue-50 p-2 rounded flex items-start">
                          <div className="bg-travel-blue text-white p-1 rounded mr-2">
                            <span className="text-xs">Day 2</span>
                          </div>
                          <div className="text-sm">
                            <p>Notre-Dame Cathedral & Seine River Cruise</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="flex justify-between items-center">
                      <div className="flex items-center">
                        <MapPin className="h-5 w-5 text-travel-orange" />
                        <span className="ml-1 text-sm text-gray-600">Generated by AI</span>
                      </div>
                      <Button size="sm" className="bg-travel-blue hover:bg-travel-blue/90">View Full Plan</Button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
